version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install boto3
      - pip install awscli

  pre_build:
    commands:
      - echo "Pre-build phase started"
      - python prebuild.py  # Notify start of build

  build:
    commands:
      - echo "Build phase started"
      - # Your build commands here

  post_build:
    commands:
      - echo "Post-build phase started"
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 1 ]; then export BUILD_STATUS="SUCCEEDED"; else export BUILD_STATUS="FAILED"; fi
      - echo "BUILD_STATUS=$BUILD_STATUS"
      - sleep 30
      - python post_build.py  # Notify end of build with status
      - echo "Triggering AWS CodePipeline..."
      - export PIPELINE_NAME="test"
      - aws codepipeline start-pipeline-execution --name $PIPELINE_NAME
      - export CODEPIPELINE_EXECUTION_ID=$(aws codepipeline list-pipeline-executions --pipeline-name $PIPELINE_NAME --max-items 1 --query 'pipelineExecutionSummaries[0].pipelineExecutionId' --output text)
      - echo "Retrieved CODEPIPELINE_EXECUTION_ID=$CODEPIPELINE_EXECUTION_ID"
      - echo "Running pipeline.py with PIPELINE_NAME=$PIPELINE_NAME and CODEPIPELINE_EXECUTION_ID=$CODEPIPELINE_EXECUTION_ID"
      - python pipeline.py

artifacts:
  files:
    - '**/*'
