version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install boto3

  pre_build:
    commands:
      - echo "Pre-build phase started"
      - python mail.py  # Notify start of build

  build:
    commands:
      - echo "Build phase started"
      - # Your build commands here

  post_build:
    commands:
      - echo "Post-build phase started"
      - python mail.py  # Notify end of build with status

artifacts:
  files:
    - '**/*'
